apiVersion: v1
kind: Service
metadata:
  name: external
  labels:
    release: "{{ .Release.Name }}"
    chartName: "{{ .Chart.Name }}"
    chartVersion: "{{ .Chart.Version }}"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    release: "{{ .Release.Name }}"
