{{- if (.Values.external) and (.Values.external.domain) and .Values.external.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    release: "{{ .Release.Name }}"
spec:
  rules:
  - host: {{ .Values.external.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.external.port }}
{{- end -}}
