{{- if (.Values.container) and .Values.container.port -}}
{{- if (.Values.external) and .Values.external.port -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Release.Revision }}"
  labels:
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
    chartName: "{{ .Chart.Name }}"
    chartVersion: "{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - name: port-{{ .Values.external.port }}
    port: {{ .Values.external.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
    chartName: "{{ .Chart.Name }}"
    chartVersion: "{{ .Chart.Version }}"
{{- end -}}
{{- end -}}
